# Site settings
title: 坚实的幻想
SEOTitle: Fantasy
header-img: img/home-bg.jpg
email: liaoishere@gmail.com
description: "On A Clear Disk You Can Seek Forever"
keyword: ""
url: "http://liaoph.com"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'
author: "Paco"
timezone: "+0800"
future: true

# SNS settings
RSS: true
weibo_username:     aoLiii
#zhihu_username:     liaopenghui
github_username:    paco0x
twitter_username:  paco0x
#facebook_username:  huxpro

# Build settings
highlighter: rouge
permalink: pretty
archive_path: archives
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Plugins
# from PR#40, to support local preview for Jekyll 3.0
plugins:
  - jekyll-paginate
  - jekyll-feed

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: rouge


# Disqus settings
disqus_username: liaoph                  # set to false if you want to use Comment without Sharing

# Analytics settings
# Baidu Analytics
ba_track_id: ca24cc0fb86c19c1a88f5f7a020629d3
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Proudly uncool and out of fashion"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value
